/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author fer
 */
public class NewJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fER_ConectorBD1 = new bean_11_consultaSQL.FER_ConectorBD();
        fER_ConsultaSQLCLIENTE = new bean_11_consultaSQL.FER_ConsultaSQL();
        fER_ConsultaSQLMUNICIPIO = new bean_11_consultaSQL.FER_ConsultaSQL();
        fER_ConsultaSQLPROVINCIA = new bean_11_consultaSQL.FER_ConsultaSQL();
        jScrollPane1 = new javax.swing.JScrollPane();
        fER_DBGRID1 = new bean_11_consultaSQL.FER_DBGRID();
        jScrollPane2 = new javax.swing.JScrollPane();
        fER_DBGRID2 = new bean_11_consultaSQL.FER_DBGRID();
        jScrollPane3 = new javax.swing.JScrollPane();
        fER_DBGRID3 = new bean_11_consultaSQL.FER_DBGRID();
        fER_NumeroColumnas1 = new bean_11_consultaSQL.FER_NumeroColumnas();
        fER_NumeroFilas1 = new bean_11_consultaSQL.FER_NumeroFilas();
        fER_NumeroColumnas2 = new bean_11_consultaSQL.FER_NumeroColumnas();
        fER_NumeroFilas2 = new bean_11_consultaSQL.FER_NumeroFilas();
        fER_NumeroColumnas3 = new bean_11_consultaSQL.FER_NumeroColumnas();
        fER_NumeroFilas3 = new bean_11_consultaSQL.FER_NumeroFilas();
        jScrollPane4 = new javax.swing.JScrollPane();
        bean_11_consultaSQL.JAreaEscucha jAreaEscucha1 = new bean_11_consultaSQL.JAreaEscucha();

        fER_ConectorBD1.setAA_BaseDatos("mis_clientes");

        fER_ConsultaSQLCLIENTE.setAA_FER_ConectorBD(fER_ConectorBD1);
        fER_ConsultaSQLCLIENTE.setConsultaSELECT("select * from cliente");

        fER_ConsultaSQLMUNICIPIO.setAA_FER_ConectorBD(fER_ConectorBD1);
        fER_ConsultaSQLMUNICIPIO.setConsultaSELECT("SELECT * FROM MUNICIPIO");

        fER_ConsultaSQLPROVINCIA.setAA_FER_ConectorBD(fER_ConectorBD1);
        fER_ConsultaSQLPROVINCIA.setConsultaSELECT("SELECT * FROM PROVINCIA");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fER_DBGRID1.setAA_FER_ConsultaSQL(fER_ConsultaSQLCLIENTE);
        jScrollPane1.setViewportView(fER_DBGRID1);

        fER_DBGRID2.setAA_FER_ConsultaSQL(fER_ConsultaSQLMUNICIPIO);
        jScrollPane2.setViewportView(fER_DBGRID2);

        fER_DBGRID3.setAA_FER_ConsultaSQL(fER_ConsultaSQLPROVINCIA);
        jScrollPane3.setViewportView(fER_DBGRID3);

        fER_NumeroColumnas1.setAA_ConsultaSQL(fER_ConsultaSQLCLIENTE);

        fER_NumeroFilas1.setAA_ConsultaSQL(fER_ConsultaSQLCLIENTE);

        fER_NumeroColumnas2.setAA_ConsultaSQL(fER_ConsultaSQLMUNICIPIO);

        fER_NumeroFilas2.setAA_ConsultaSQL(fER_ConsultaSQLMUNICIPIO);

        fER_NumeroColumnas3.setAA_ConsultaSQL(fER_ConsultaSQLPROVINCIA);

        fER_NumeroFilas3.setAA_ConsultaSQL(fER_ConsultaSQLPROVINCIA);

        jAreaEscucha1.setColumns(20);
        jAreaEscucha1.setRows(5);
        jAreaEscucha1.setToolTipText("");
        jAreaEscucha1.setWrapStyleWord(true);
        jAreaEscucha1.setAA_JAreaAsociada(jAreaEscucha1);
        jAreaEscucha1.setAA_PropiedadAcomprobarSiCambia("");
        jAreaEscucha1.setAA_VerCambiosEnElContenedor(true);
        jAreaEscucha1.setAA_borraTexto(false);
        jScrollPane4.setViewportView(jAreaEscucha1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(fER_NumeroColumnas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(fER_NumeroFilas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(fER_NumeroColumnas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(fER_NumeroFilas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(fER_NumeroColumnas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(fER_NumeroFilas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fER_NumeroColumnas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fER_NumeroFilas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fER_NumeroColumnas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fER_NumeroFilas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fER_NumeroColumnas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fER_NumeroFilas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 280, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bean_11_consultaSQL.FER_ConectorBD fER_ConectorBD1;
    private bean_11_consultaSQL.FER_ConsultaSQL fER_ConsultaSQLCLIENTE;
    private bean_11_consultaSQL.FER_ConsultaSQL fER_ConsultaSQLMUNICIPIO;
    private bean_11_consultaSQL.FER_ConsultaSQL fER_ConsultaSQLPROVINCIA;
    private bean_11_consultaSQL.FER_DBGRID fER_DBGRID1;
    private bean_11_consultaSQL.FER_DBGRID fER_DBGRID2;
    private bean_11_consultaSQL.FER_DBGRID fER_DBGRID3;
    private bean_11_consultaSQL.FER_NumeroColumnas fER_NumeroColumnas1;
    private bean_11_consultaSQL.FER_NumeroColumnas fER_NumeroColumnas2;
    private bean_11_consultaSQL.FER_NumeroColumnas fER_NumeroColumnas3;
    private bean_11_consultaSQL.FER_NumeroFilas fER_NumeroFilas1;
    private bean_11_consultaSQL.FER_NumeroFilas fER_NumeroFilas2;
    private bean_11_consultaSQL.FER_NumeroFilas fER_NumeroFilas3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
